# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_clarifai_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
